export { ArticleDetails } from './ui/ArticleDetails/ArticleDetails'
export type { Article, ArticleView } from './model/types/article'
export type { ArticleDetailSchema } from './model/types/articleDetailSchema'
export { articleDetailsReducer } from './model/slice/articleDetailsSlice'
export { getArticleDetailsData } from './model/selectors/getArticleDetailsData'
export { ArticleList } from './ui/ArticleList/ArticleList'
